### ISSUE TITLE
Support for iPhone X

### ISSUE THREAD

**Issue by kpiwko** [freeotp/freeotp-ios#101]
Please consider adding support to cover iPhone X layout. This is how it renders currently

![img_0048](https://user-images.githubusercontent.com/355881/36675787-41b7d126-1b0a-11e8-89b5-f8caad2d0e39.jpg)

**Comment by justin-stephenson** [comment]
@kpiwko Can you confirm if `FreeOTP v2.0` addresses this problem for you?

**Comment by kpiwko** [comment]
Yes, it works with notch now @justin-stephenson . Thanks!

![IMG_99CC47B50AC2-1](https://user-images.githubusercontent.com/355881/83862406-3188d880-a722-11ea-8b54-8e8f6c90a360.jpeg)
