### ISSUE TITLE
Changing order of tokens difficult for those with lots of tokens

### ISSUE THREAD

**Issue by bexelbie** [freeotp/freeotp-ios#103]
Having more than a screen full of tokens, results in tokens being hard to rearrange.  On iOS the token you're moving gets "exponential" speed and you scroll fast.  Can we move to a system of move touch points and slower scroll speed to fix this?

See also #23

**Comment by justin-stephenson** [comment]
Agreed, this still needs to be fixed.

**Comment by justin-stephenson** [comment]
@bexelbie Could you test this with the latest v2.2 release(released today) and let me know if it addresses your concerns

**Comment by bexelbie** [comment]
It does! Thank you
