### ISSUE TITLE
FreeOTP crashes on ios 11.4 when accessing the camera without permission

### ISSUE THREAD

**Issue by sirwalrus** [freeotp/freeotp-ios#104]
On ios 11.4 -> settings -> Privacy -> Camera -> disable FreeOTP from having camera access
Then...
Open FreeOTP -> Hit QR button -> app crashes rather than telling you it lacks permission

**Comment by mhyzon** [comment]
And now in iOS 12, I am guessing  the permissions model changes and FreeOTP doesn't (or can't) ask for permission to use the camera.

**Comment by sabbaka** [comment]
Permission issue was resolved in latest v1.2 release for iOS.
