### ISSUE TITLE
PIN code?

### ISSUE THREAD

**Issue by ronaldo48a** [freeotp/freeotp-ios#105]
Can we add PIN code function to open the app? it is very necessary for the smartphone.

**Comment by maietta** [comment]
Seems to me you already have this feature as part of iOS or Android devices. Not needed for the app itself. Could you explain why you feel the need for a pin on an app?

**Comment by alexgpdx** [comment]
> Seems to me you already have this feature as part of iOS or Android devices. Not needed for the app itself. Could you explain why you feel the need for a pin on an app?

This assumes one device = one user, which isn't always the case. Adding a PIN and/or biometric ID to use the app is a good idea.

**Comment by Githubuxer** [comment]
Agreed, I have many apps that use additional biometrics such as ProtonMail.

**Comment by james-182** [comment]
Adding a PIN and/or biometric ID to use the app is a good idea.

**Comment by npmccallum** [comment]
We already have support for locked tokens, which require recent authentication in order to activate. I suspect adding authentication for the whole app would probably be counter-productive.

@ronaldo48a @Githubuxer @james-182 Why don't locked tokens work for you?

**Comment by Githubuxer** [comment]
What do you mean by locked tokens? On iOS there isn’t even an info/setting button?

**Comment by npmccallum** [comment]
@Githubuxer On FreeOTP 2.0, when you create a token you're given the option to have it "locked", that is to require authentication before showing the token code. Try it out. I suspect it will fit your needs.

**Comment by Githubuxer** [comment]
So how does this relate to migrated tokens?

**Comment by justin-stephenson** [comment]
@Githubuxer You would need to remove and re-add tokens to take advantage of this v2.0 feature for migrated tokens.

In version 2.0 the Scan token wizard will prompt you to optionally enable Touch ID locking, FaceID support will be added in #150
