### ISSUE TITLE
Freezes on iOS

### ISSUE THREAD

**Issue by hasanen** [freeotp/freeotp-ios#108]
I've noticed today some occasional freezes with the FreeOTP in iOS 12.

After leaving the app on background for a while and bringing it back, nothing happens. After killing the app and starting the app again, I'm able to use the app normally. 

How to reproduce the freezing:
1. open the app and close it (go to desktop for example)
2. Lock the screen and let the phone be locked for few seconds
3. Unlock the phone and open the app
4. Can't scroll with the list

My phone is iPhone X with iOS 12 and the app is the latest from app store.

**Comment by lightswitch05** [comment]
I've seen this same behavior on my iPhone XS with iOS 12.0.1

**Comment by lightswitch05** [comment]
Looking at the state of the iOS and [Android app](https://github.com/freeotp/freeotp-android/issues/201) - it appears this project has been abandoned. For iOS [Authenticator](https://github.com/mattrubin/Authenticator) looks like a great opensource alternative for those who wish to avoid the google authenticator

**Comment by gesunwei** [comment]
I have the same issue with IOS 12.1.2, in IOS 11 everything is fine...

**Comment by hasanen** [comment]
Haven't faced the freezes since the last update, great!
