### ISSUE TITLE
Does not work on IOS 12.1 and before that was buggy

### ISSUE THREAD

**Issue by barrydegraaff** [freeotp/freeotp-ios#111]
This app used to work well, till about 6 months ago.

Problem is that this app no longer asks for camera permission.

Till ios 12, one could start the app, het the QR code for scanning, that would crash the app. But it would appear in the list for devices that asked for permission. Going in that list and tap allow would work around the issue.

In ios 12.1 the app freezes, but also does not appear in the list anymore, resulting in no camera permission, resulting in an app that does not work.

This is a serious issue for us, as we have rolled it out to some 700 users, and now new users or users with new phones cannot use this anymore.

related:
https://github.com/freeotp/freeotp-ios/issues/108
https://github.com/freeotp/freeotp-ios/issues/104

**Comment by barrydegraaff** [comment]
@npmccallum since there are `no people` in the freeptp organization in Github, may I ask you who I should talk to, to get this app fixed? Anybody at RedHat we can push? As they seem to be the owners on the app store? Please let me know, thanks!

**Comment by sandeep1213** [comment]
@barrydegraaff 

I am too facing the same issue and opened a RedHat case, I am redirected to this by RedHat support.

**Comment by barrydegraaff** [comment]
Nice they directed you here, but herenothing seems to happen...

**Comment by barrydegraaff** [comment]
As per suggestion in issue 108 I moved some users to another open-source solution 
that works in ios 12.1

https://github.com/mattrubin/Authenticator
pointing to
https://itunes.apple.com/us/app/authenticator/id766157276

**Comment by barrydegraaff** [comment]
That is funny, because it is released by `RedHat` on the Apple Store, but at least we know
what's what.

Can you update the support call to indicate that, I have a feeling they might have
missed that.

Thanks.

**Comment by sandeep1213** [comment]
@barrydegraaff ,

I updated same to case and waiting for their response about app being released by them and now not answering about issues. I will update as I hear back.

Also can I know what are you using this FreeOTP app for ? I am using this in conjunction with RedHat IdM you too using it for same purpose ? I am curious to know, whether the other apps you suggested would work with IdM.

**Comment by sandeep1213** [comment]
My RedHat case is closed with following response.

"Yes, FreeOTP is shipped/released by Red Hat but it is an open source community maintained implementation of the TOTP and HOTP.
As a community maintained product it is unsupported as described at Production Support Scope of Coverage"

**Comment by justin-stephenson** [comment]
@barrydegraaff @sandeep1213 Can you confirm if this issue is resolved in `FreeOTP v2.0` released on the App Store?

**Comment by barrydegraaff** [comment]
@justin-stephenson yes after 2 years it works again! Too bad we had to move all our users over to a different app.

Nice that the new version also offers an option to select recognizable icons for each token!

**Comment by barrydegraaff** [comment]
(tested on iOS 13.4)
