### ISSUE TITLE
Free OTP app not working on IOS12.1

### ISSUE THREAD

**Issue by sandeep1213** [freeotp/freeotp-ios#112]
Whenever I try to scan a bar code with freeOTP app it just blanks  out and I am not able to get the OTP. I use this in conjunction to RedHat IdM for enabling MFA. I opened case with RedHat support, but I am told to open up an issue here.

**Comment by ronaldtse** [comment]
QR code functionality doesn't work on the latest iOS. Was great when it worked. 😢

**Comment by MateMathieu** [comment]
> QR code functionality doesn't work on the latest iOS. Was great when it worked. cry

Same thing here. Please can you refresh this app? I use it every single day of the year...

It enables higher grade of security for servers and authentication for everyone without hassle. It is too useful to be abandoned. Thank you so much for the work already done, but a little more support would make it amazing! 
Faithfully

**Comment by sabbaka** [comment]
Hi all
Please, try to re-enable camera permission in setting of FreeOTP in iOS. I just tried this and I was able to add by QR code.

**Comment by sabbaka** [comment]
I've tested it and found a way to ask for permission. I'll need to do some additional checks and might fire a release only for this particular issue or maybe with some more fixes. I will keep you guys posted.

**Comment by kashbadami** [comment]
I downloaded the source and recompiled the app for my iPhone. The recompile
works. I had to make several other changes to get it to build for iPhone XR
using Xcode 12.x. Once recompiled and installed it worked just fine. I’ll
try to get a list of the things I had to tweak on the project for it to
compile. In particular it could not find some libs that I had to get
downloaded and recompiled.

**Comment by jpryals58** [comment]
I'm seeing the same issue, and FreeOTP isn't showing up in the app list on my settings menu (so I can't change the camera permissions for it). Hoping for an update.

**Comment by kashbadami** [comment]
Thats correct. There is no way to disable/enable access to the camera for
freeotp. It does not appear in the list of apps that have access to the
camera or are requesting access to the camera. I believe this has to do
with the current build not being compiled for the latest versions of the OS
and hardware.

**Comment by emacsomancer** [comment]
It would be nice to get a fix for this.

**Comment by ctueck** [comment]
Had the same camera issue. Cool to see the fix already done, but I assume that's not yet in the version on App Store? Will gladly re-try the app when it's there!

**Comment by sabbaka** [comment]
> Had the same camera issue. Cool to see the fix already done, but I assume that's not yet in the version on App Store? Will gladly re-try the app when it's there!

It is not yet in AppStore. The plan is to test it first before the release. 
I am creating the way to distribute application for testing first. It is more complicated for iOS than for Android.
Once it will be tested I will make a minor release to fix current problem for iOS 12.1.

**Comment by MichaelJahn2** [comment]
Hi,

thanks for working on this. Any update on the progress / timeline.

**Comment by Sslimon** [comment]
I had the same problem. Following worked for me:
I scanned the barcode with normal camera app and then a banner appeared and asked if I want to open it with the otp app. When I tapped on the banner it worked.

**Comment by orev** [comment]
Please try to release this fix asap.  This is a complete showstopper to getting new users setup with multi-factor.

**Comment by sabbaka** [comment]
> Please try to release this fix asap. This is a complete showstopper to getting new users setup with multi-factor.

The fix is done and is in process of testing. I think the release will be done on the next week.

**Comment by MateMathieu** [comment]
Thank you!

**Comment by Mr-Morden** [comment]
> 
> 
> I had the same problem. Following worked for me:
> I scanned the barcode with normal camera app and then a banner appeared and asked if I want to open it with the otp app. When I tapped on the banner it worked.

Many thanks Sslimon!  Worked for me also today 20.2.2019 (--> iPhone iOS 12.1.4, FreeOTP app, when setting Posteo two-factor authentication)

**Comment by sabbaka** [comment]
Just an update. Release is in progress. I am working on it. 
It is required by Apple to provide screenshots for bunch of screen sizes, so I am about to finish this and then there will be a review process from them. I'll keep posting in this thread.

**Comment by madarche** [comment]
A working version of FreeOTP for iOS12 can now be found on the App Store https://itunes.apple.com/us/app/freeotp-authenticator/id872559395. We tried it and it works. Thanks a lot for your work! Can this issue be considered solved?

**Comment by sabbaka** [comment]
> A working version of FreeOTP for iOS12 can now be found on the App Store https://itunes.apple.com/us/app/freeotp-authenticator/id872559395. We tried it and it works. Thanks a lot for your work! Can this issue be considered solved?

Thanks a lot for posting. Yes, the release was done and I selected an option to release it within a week period, gradually.
Let's get some more positive feedback and then I will close the issue.

P.S. > next step will be fixing the bug with wide angle cameras on some iPhone models.

**Comment by MateMathieu** [comment]
Same on my side, the app properly request authorization to access the phone camera after I select the QR code registration scheme.

**Comment by sabbaka** [comment]
Issue was resolved.
