### ISSUE TITLE
Migrating FreeOTP from iphone to android

### ISSUE THREAD

**Issue by veronduh** [freeotp/freeotp-ios#113]
Hey there! I recently switched from iphone to android. I had FreeOTP on my iphone and need to find a way to migrate it to my android. 
I found these two posts: 
[(https://lists.fedoraproject.org/archives/list/freeotp-devel@lists.fedorahosted.org/message/AVKVOEPZVIO5H5XVW334GAWES5CQ7BXM/)]

[https://thevaliantway.com/2018/08/freeotp-migration/]

But both seem to be going from android to android. Also, I would rather not root my android yet as it is brand new. 

Any help is greatly appreciated, thanks!

**Comment by sabbaka** [comment]
Hey,
This will require the export/backup feature. I am looking into it, but it might not be delivered soon.

**Comment by veronduh** [comment]
Thanks for the quick response and for being honest with delivery time haha. No worries, hopefully the accounts will send me a new qr code to scan.

Thanks again!

**Comment by katierik** [comment]
Export/backup would also be great when going from Android to iphone (as I have just been struggline with)

**Comment by jacek-1** [comment]
perhaps you could also give a hint how to migrate from OTP app from android to freeOTP on iOS (with not-rooted iPhone)  ?
