### ISSUE TITLE
no more QR-code scanning with IOS > 12.1

### ISSUE THREAD

**Issue by UweFr** [freeotp/freeotp-ios#115]
Please fix the problem!

**Comment by orev** [comment]
This is ridiculous.  How can such a simple app be languishing like this?!

**Comment by yohhad5** [comment]
Still it is not working can you please fix the issue.

**Comment by yohhad5** [comment]
Thx for the fix, it is working prfectly.

**Comment by sabbaka** [comment]
Thank you for a positive feedback.
