### ISSUE TITLE
Multiple Instance for the same issuer

### ISSUE THREAD

**Issue by ebal** [freeotp/freeotp-ios#116]
Hello,

I am using FreeOTP v1.2 for IOS 12.1.4
and I have an issue adding multiple OTPs from the same (cloud) issuer.

Every QR from a different tenant, comes with:

```
issuer: huawei
username: ebal
```

When using Google Authenticator, I see on my mobile that adds 

- huawei
- huawei_1
- huawei_2
- huawei_3

etc but in FreeOTP every new QR scan, tries to replace the first one.

I've tried to rename it, but I still can not add any new OTP from the same issuer. 

Thanks in advance,

**Comment by sabbaka** [comment]
Thank you for reporting. I think this is a must have feature. I'' try to implement it soon.

**Comment by Steve-Z** [comment]
Same issue here, using Namecheap's Private Email. I have two accounts. Even if I edit the name and ID of the first one, the second scan of QR code just replaces it.

**Comment by justin-stephenson** [comment]
@ebal @Steve-Z Can you confirm if this issue is resolved in `FreeOTP v2.0` released in the App Store?

**Comment by justin-stephenson** [comment]
Please re-open if necessary, this should be resolved.
