### ISSUE TITLE
Entries shrinked and labels are tiny unreadable

### ISSUE THREAD

**Issue by AS-Igel** [freeotp/freeotp-ios#117]
With the latest update (version 1.2) the width of each entry now is only a good half of the screen size (at least on an iPhone 8). The labels became tiny unreadable.
There's no default icon neither.
![img_0949](https://user-images.githubusercontent.com/22155695/54032498-142d2d80-41b2-11e9-87ad-ca4c4f36a45f.PNG)
Note: the labels in this example are pixelized; it's just to show the waste of space on the screen

**Comment by sabbaka** [comment]
I will take a look. Thank you for bug report.

**Comment by CoalaJoe** [comment]
+1

**Comment by dajappie** [comment]
+1, same issue here on iPhone 7 with iOS 12.3.1

**Comment by Githubuxer** [comment]
Any updates on this issue? Great app, but looking at android screenshots, this is still a major iOS bug.

**Comment by justin-stephenson** [comment]
This will be fixed in the next version 2.0 release on iOS

**Comment by justin-stephenson** [comment]
@AS-Igel @CoalaJoe Can you confirm if this issue is resolved in FreeOTP v2.0 released in the App Store?

**Comment by justin-stephenson** [comment]
Please re-open if necessary, this should be resolved.
