### ISSUE TITLE
Deleting and Editing not working in 1.2 on iOS

### ISSUE THREAD

**Issue by LPTT** [freeotp/freeotp-ios#118]
Tried to edit and delete an entry on iPad and iPhone with Version 1.2. it is not working on either of them. I get the menu but there is no reaction on pressing the button.

**Comment by sabbaka** [comment]
> Tried to edit and delete an entry on iPad and iPhone with Version 1.2. it is not working on either of them. I get the menu but there is no reaction on pressing the button.

Thanks a lot for the bug report. I will check this. I am planning next release soon which will also fix the wide angle camera issue.

**Comment by SEXXES** [comment]
Same bug here!

**Comment by SEXXES** [comment]
Oh and by the way:

I'm missing a sync and backup function in the app... as Authy has it.

**Comment by Peappler** [comment]
Same here, not working at all! Are you planing to update? Otherwise I will delete the app.

**Comment by michaelstalker** [comment]
I'm just checking in on the status of this bug. Thanks for all your work on this!

**Comment by justin-stephenson** [comment]
Closing as resolved. Edit functionality no longer exists but removing tokens can be performed in `FreeOTP v2.0` with a Swipe right gesture.
