### ISSUE TITLE
Invalid token URI!

### ISSUE THREAD

**Issue by ndthanh1991** [freeotp/freeotp-ios#121]
I encountered this error: Invalid token URI! when install other device, but my device doesn't have this bug, please give me a solution

**Comment by justin-stephenson** [comment]
@ndthanh1991 Can you test if `FreeOTP v2.0` in the App Store resolves this issue for you?

**Comment by ndthanh1991** [comment]
> @ndthanh1991 Can you test if `FreeOTP v2.0` in the App Store resolves this issue for you?

i'm resolved the problem, because the device not set passcode.
