### ISSUE TITLE
Can’t delete

### ISSUE THREAD

**Issue by sekizuri** [freeotp/freeotp-ios#132]
Using: 
 FreeOTP 1.2 on iPad software 13.2.1

 Issue: 
I cannot delete a login entry. I press delete and nothing happens.

Other:
Latest update was 9 months ago... and ios 13 has been out for a long time; is this app dead? Are there open source alternatives to freeOTP someome can recommend?

**Comment by jicho** [comment]
For someone who it looking for a solution... you need to swipe the entry from right to left (when left to right is more normal) do delete te entry...

Another weird thing... When you delete FreeOTP and install it again all entries are preserved.
