### ISSUE TITLE
No such module and "Base32" and "moa"

### ISSUE THREAD

**Issue by LudoviKush** [freeotp/freeotp-ios#135]
I have just downloaded freeotp from the git repo but when i try to run it says "no such module" 
How can i fix this?
![Schermata 2020-02-14 alle 07 42 06](https://user-images.githubusercontent.com/39263355/74546010-2713ba80-4f4a-11ea-88ad-a4bb361491ed.png)

**Comment by justin-stephenson** [comment]
Hi @LudoviKush You need to download the linked frameworks with https://github.com/Carthage/Carthage

The command `carthage update` in the root of the git repo should download the necessary frameworks to build FreeOTP in Xcode

**Comment by gtsop** [comment]
Please add this to the README

**Comment by justin-stephenson** [comment]
This was updated in the README, if there is any other information missing please let us know.
