### ISSUE TITLE
Improve the project branding/name

### ISSUE THREAD

**Issue by MartinDelille** [freeotp/freeotp-ios#136]
What about changing the project name?

The current one is too self descriptive and not very *sexy*. Having a better branding would bring more users, more feedback and more funding.

This is just a suggestion but maybe we could start a thread to push up ideas, no?

**Comment by MartinDelille** [comment]
What about *Trousseau*? It is a french word that mean keychain. It also contains the name of [a famous french philosopher](https://en.wikipedia.org/wiki/Jean-Jacques_Rousseau).

**Comment by justin-stephenson** [comment]
I will defer to @npmccallum on this

**Comment by npmccallum** [comment]
We will keep the current name.
