### ISSUE TITLE
Don't scan my gitlab two factor authentification QR code

### ISSUE THREAD

**Issue by MartinDelille** [freeotp/freeotp-ios#137]
I tried to enable two factor authentification on gitlab without success: https://gitlab.com/profile/two_factor_auth

The QR code scanning feature doesn't work.

Usually, QR code display a framing to help position the QR code in the preview. Maybe it would help?

**Comment by justin-stephenson** [comment]
Hi @MartinDelille are you getting an error, does the app crash, or does the QR code scan never register ? 

I tested this on my end without issues, so I'd like to know more about what you are seeing on your side.

**Comment by MartinDelille** [comment]
Sorry: "doesn't work" isn't very explicit.

The QR code scan never register.

**Comment by justin-stephenson** [comment]
@MartinDelille Can you please check if this issue is resolved in `FreeOTP v2.0` available in the App Store?

**Comment by justin-stephenson** [comment]
Please re-open this issue if still applicable.
