### ISSUE TITLE
Edit button does not visually prompt user to click on token card

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#141]
When you click the edit button, nothing changes with the token card to prompt the user to click on the token card.

The scan bar becomes greyed out and the ‘edit’ changes to ‘done’, but a user will have to experiment to realize that they can click on token card to bring up menu, because nothing changes visually with the token card when you hit edit.

You just need to know from experience that you can now click on the token card.

**Comment by justin-stephenson** [comment]
Closing as outdated with edit functionality removed.
