### ISSUE TITLE
Add About/Feedback menu item

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#143]
The app is missing any kind of information relating to where it came from, who made it, where you can submit for help/feedback, version number and privacy/terms.

After seeing screenshots here https://freeotp.github.io/ it seems the Android version has an info button but iOS does not.

**Comment by Githubuxer** [comment]
Just updated to the new release, there is still zero information about the app while inside it and no feedback section.

**Comment by justin-stephenson** [comment]
Yes, we do not yet have an Info button. Currently, the App store shows `Red Hat` as the developer and `App Support` button links to the the **FreeOTP-iOS** github issues page.

**Comment by justin-stephenson** [comment]
Android about me information:

https://github.com/freeotp/freeotp-android/blob/master/app/src/main/res/values/strings.xml

https://github.com/npmccallum/freeotp-android/blob/master/mobile/src/main/res/values/strings.xml

**Comment by justin-stephenson** [comment]
Fixed in [v2.1](https://github.com/freeotp/freeotp-ios/releases/tag/v2.1)
