### ISSUE TITLE
FreeOTP doesn't start on iOS 13.4.1

### ISSUE THREAD

**Issue by thematt** [freeotp/freeotp-ios#145]
Hello!
After upgrading iOS to 13.4.1, FreeOTP does not start more, screen record -https://i.imgur.com/LkjROsm.mp4.

FreeOTP 1.2, iOS 13.4.1, iPhone 7.

**Comment by thematt** [comment]
I've upgraded to new iOS 13.5.1, but it didn't help :(

**Comment by justin-stephenson** [comment]
Hello @thematt, there is a new version 2.0 available now on the App Store. Could you test to see if it works for you?

**Comment by thematt** [comment]
@justin-stephenson Hello, yes, now it is working! Thanks a lot, I was really looking forward to it!
