### ISSUE TITLE
RFE: Add ability to copy a token code

### ISSUE THREAD

**Issue by justin-stephenson** [freeotp/freeotp-ios#149]
FreeOTP v2.0 Beta feedback:

Alright, one addition I would love in the iOS app. The ability to copy a token code. If the feature is already there I haven't been able to find it via the normal iOS patterns.

**Comment by Githubuxer** [comment]
Same, trying to switch to this app from Google Authenticate but not able to copy to clipboard, unless this is a security issue? Can apps snoop on clipboard?

**Comment by justin-stephenson** [comment]
This functionality already exists when clicking on the 'Share' text in the token cell

**Comment by Githubuxer** [comment]
What share text?

**Comment by justin-stephenson** [comment]
@Githubuxer this will be in the new version 2.0 available soon on the App Store.

**Comment by Githubuxer** [comment]
Why does clicking share ask for bluetooth? I'm just trying to copy and paste the code on the same device?

Or does clicking on a token copy it? There is no visual feedback to indicate this, if this is the case.
