### ISSUE TITLE
Add Support for FaceID locking/unlocking

### ISSUE THREAD

**Issue by justin-stephenson** [freeotp/freeotp-ios#150]
from FreeOTP v2.0 Beta Feedback

**Comment by fellipeh** [comment]
+1

**Comment by mateMathieu** [comment]
+1, touchID as well.

**Comment by justin-stephenson** [comment]
Fixed in [v2.1](https://github.com/freeotp/freeotp-ios/releases/tag/v2.1)

**Comment by mateMathieu** [comment]
Hi, I must have missed something @justin-stephenson. Where shall I activate/deactivate these features within the app?
Thanks

**Comment by justin-stephenson** [comment]
@mateMathieu When scanning a new OTP QR code, you will be prompted to enable Locking for that specific token. This will enable the FaceID (or TouchID) requirement to display the token code.
