### ISSUE TITLE
Please use grey or customizable colour instead of strange green that is clashing with custom icon colours.

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#154]
The green behind all the custom icons clashes with all icon colours.

What is the signifigance of the thick green border? If this represents something, is there no better way to use it rather than outline all the custom icons?

**Comment by justin-stephenson** [comment]
Thanks for the feedback @Githubuxer - this was an unintended side effect of the new token icon feature, we will make sure to fix this problem for migrated custom icon tokens.

**Comment by Githubuxer** [comment]
Got it, so is there no way to remove/edit the token icons any longer? Or how does that work?

**Comment by justin-stephenson** [comment]
You can re-add any existing migrated tokens to take advantage of the new token icon feature.

We can also create a manual mapping from an Issuer name to a Font Awesome icon, this requires that the brand icon that you want to use is already in Font Awesome. You can submit a Pull Request for this `Issuer -> Icon` mapping by adding to the collection here, it will be hardcoded into FreeOTP.
  
https://github.com/freeotp/freeotp-ios/blob/5b35edb8db43d7c01fa88ff74ac1a0f8ee584690/FreeOTP/TokenIcon.swift#L303

**Comment by Githubuxer** [comment]
Got it, how do you edit icons now? I can’t seem to figure it out, unless this is an issue with migrated icons.

**Comment by justin-stephenson** [comment]
The editing functionality after a token is stored(like with migrated tokens/icons) was removed in v2.0.

**Comment by Githubuxer** [comment]
Got it, so only way is to delete token and re-add?

**Comment by justin-stephenson** [comment]
Yes, that's correct @Githubuxer

**Comment by justin-stephenson** [comment]
Fixed in [v2.1](https://github.com/freeotp/freeotp-ios/releases/tag/v2.1)
