### ISSUE TITLE
Active Token - Inner circle and outer ring not in sync

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#155]
What is the significance of inner circle and outer ring?

Sometimes they are in sync, sometimes they are not, Other authentication apps just use the inner circle for visual simplicity.

It is very confusing to understand how long the token is good for when the inner and outer circle do not match up, unless they represent different information?

**Comment by justin-stephenson** [comment]
This is for TOTP tokens: the inner circle progress timer represents the validity of the token, it completes when the time step has passed(default 30 seconds). When the inner circle progress completes a new valid token should automatically be computed and displayed.

The outer ring will show the progress of the initial and the next totp token codes.
