### ISSUE TITLE
Share code clipboard function hidden behind bluetooth request, and 'copy to clipboard' text hidden behind black bar.

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#156]
In the latest update you have to close/dismiss the bluetooth request box just to be able to get to the copy locally button.

When you get to the local option, the 'copy to clipboard' text, it is almost completely blacked out, like a very dark grey, almost impossible to read.

The local copy to clipboard needs to not be hidden behind a bluetooth request, and the copy to clipboard text needs to have the BG colour adjusted so it is visible.

**Comment by justin-stephenson** [comment]
Thanks @Githubuxer we will discuss how we can improve the user experience for copying to clipboard and address the blacked out/hidden text issue.

**Comment by agiertli** [comment]
In previous version the generated token was copied to clipboard automatically. Can we bring this functionality again?

**Comment by justin-stephenson** [comment]
@agiertli This functionality was removed to avoid leaking token codes unintentionally

**Comment by pplch** [comment]
I also lack the ability to automatically copy to the clipboard.
Unfortunately, the Sharing option does not work.
I tested repeatedly between iPhone-Macbook, iPhone-iPad, iPhone-MacMini.
As a result, I've temporarily started using Google Authenticator.

**Comment by agiertli** [comment]
@justin-stephenson understand - but it makes far worse UX. Is there any way how I can easily rollback my FreeOTP app to an older version? This is a deal breaker functionality for me personally.

**Comment by npmccallum** [comment]
@pplch Click "Share". Click "Copy to Clipboard". I'm not sure where the problem lies.

**Comment by agiertli** [comment]
The "copy to clipboard" button is pitch black with a pitch black text. I
had no idea it had some text on it until some guys on memo list mentioned
it. The no contrast just makes it not readable.

**Comment by npmccallum** [comment]
@agiertli That seems like a legitimate bug. @justin-stephenson Please investigate.

**Comment by justin-stephenson** [comment]
@agiertli This was fixed in https://github.com/freeotp/freeotp-ios/commit/71ecdc9c36a6b0a47dd6e61f770e689cf4784fcd and will be included in the next minor bug fix release

**Comment by pplch** [comment]
It works now.
I had to delete all tokens, then re-added them.
Now it works without problems: "Tap" Share -> "Tap" Copy to Clipboard.
Thank you very much.

**Comment by Githubuxer** [comment]
The other UX issue here, is that you are asking the user to click on the 'share' text without knowing what the status/expiry of the current token is, because to check the token, it hides the share button,  and you can not get back to it. The user needs to see the status of the token expiry to ensure they have enough time to copy/paste token.

**Comment by ecki** [comment]
The copy to clipboard works, but it should not ask for BT permissions

**Comment by npmccallum** [comment]
> The other UX issue here, is that you are asking the user to click on the 'share' text without knowing what the status/expiry of the current token is, because to check the token, it hides the share button, and you can not get back to it. The user needs to see the status of the token expiry to ensure they have enough time to copy/paste token.

This is not a problem in practice. OTP servers almost always allow multiple tokens to be valid at once. For example, if you're using TOTP, you typically get something like +/- 3-10 tokens valid at once. So there is really no need to worry about the expiry of the current token.

**Comment by justin-stephenson** [comment]
The copy-to-clipboard/Share scene UI issue is fixed in [v2.1](https://github.com/freeotp/freeotp-ios/releases/tag/v2.1)

Any other issues should be separated out into different tickets.
