### ISSUE TITLE
Button to add/edit token missing 

### ISSUE THREAD

**Issue by ecki** [freeotp/freeotp-ios#167]
Since one of the latest updates I don't have a + button to add a token from the text code anymore. I only have the QR code dialog, which does not so much work if you have the web site on the device.

Also I don't find a edit function and the remove swipe is quite strange with the bubble on button of the screen
![CFDBA55B-5A87-4651-8BCA-58F7F04D62AF](https://user-images.githubusercontent.com/361432/84651865-ea150000-af0a-11ea-9f3c-db6ea6823e1d.jpeg)

**Comment by justin-stephenson** [comment]
@ecki Thanks for the feedback, you can open a otpauth URL link if you don't have a QR code available to scan. Noting this as duplicate of https://github.com/freeotp/freeotp-ios/issues/138

**Comment by ecki** [comment]
Duplicate
(Btw I stopped FreeOTP as there was no good keychain protection, now that this is fixed the features and ux seems to not invite to come back...)
