### ISSUE TITLE
No option to enter manual key

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#168]
Where is the option to enter key manually on iOS? I can’t scan the barcode if I’m using the same device.

**Comment by npmccallum** [comment]
Click the OTP URI or token code. Your vendor should have made it a clickable link. If not, I *think* you can copy/paste the URI into a browser and it should forward it to FreeOTP.

**Comment by Githubuxer** [comment]
Thanks, I'll try that next time.
