### ISSUE TITLE
When you are dragging token, other token cards being dragged over become same icon as one being dragged

### ISSUE THREAD

**Issue by Githubuxer** [freeotp/freeotp-ios#170]
When you are dragging a token tile, the token tiles you are dragging over become the same icon as the one you are dragging.

This is a mix of new and migrated tokens.

**Comment by justin-stephenson** [comment]
Thanks @Githubuxer for reporting this issue, I see the problem as well, it looks like a Cell re-use issue and we should definitely fix it.

**Comment by Githubuxer** [comment]
Not sure if it is related or should be posted as separate issue but it is extremely difficult to drag items where you want them to go.

**Comment by justin-stephenson** [comment]
> Not sure if it is related or should be posted as separate issue but it is extremely difficult to drag items where you want them to go.

We have that in https://github.com/freeotp/freeotp-ios/issues/103

**Comment by justin-stephenson** [comment]
@Githubuxer Can you test this with FreeOTP v2.2 and let me know if it helps?

**Comment by Githubuxer** [comment]
Very nice! Works perfectly.
