### ISSUE TITLE
New GUI or hacked ?

### ISSUE THREAD

**Issue by Hoperightnow** [freeotp/freeotp-ios#171]
Since I updated freeOPT recently, the GUI and the icon changed dramatically.
See screenshot.
I wonder if I can still use the app safely.

Thanks 

![Git_hub_Freeopt](https://user-images.githubusercontent.com/67196210/85204271-37c6a980-b30b-11ea-9d7c-39aee8b22ac8.jpg)

**Comment by justin-stephenson** [comment]
Hello @Hoperightnow - Yes, the UI and App Icon were updated in v2.0 - this was intended.
