### ISSUE TITLE
Latest update seems to have removed the UI

### ISSUE THREAD

**Issue by matt5019** [freeotp/freeotp-ios#176]
I have the latest update and the only button I have is the blue qr code button. I cannot backup or extract secretes. I can't edit existing entries. I was able to use it with office 365 in the past but with all the options removed scanning an office 365 qr code fails and I have no way to manually enter anything.

**Comment by justin-stephenson** [comment]
@matt5019 Thanks for reporting this issue. Existing tokens in `FreeOTP` were migrated to the Keychain store in the `v2.0` update. This is the first report that previous tokens were not migrated properly therefore it is difficult to say what caused the failure without more data.

Can you please provide(with the secret removed) the Office365, or any other OTP URI's which are failing to scan?

Please note token editing and manual token adding were removed intentionally.

**Comment by krugerk** [comment]
@matt5019 
Perhaps you are presented with a QR Code in the following:
 **configure mobile app**
1. install the microsoft authenticator app
2. in the app add an account
3. scan the image
   <image of qr code>

with an option to '*configure app without notifications*'.

If so, switch to the one for an app without notifications, which should show a qr code freeotp supports / can scan.
