### ISSUE TITLE
rewrite preferring the guard pattern to the test against nil followed by a force unwrap

### ISSUE THREAD

**Issue by krugerk** [freeotp/freeotp-ios#181]
Here is an example.

the check for nil
https://github.com/freeotp/freeotp-ios/blob/383ece850df81bc55bbdea7c8a0b5ff02eb1492b/FreeOTP/TokensViewController.swift#L226

and the force unwrap thereafter
https://github.com/freeotp/freeotp-ios/blob/383ece850df81bc55bbdea7c8a0b5ff02eb1492b/FreeOTP/TokensViewController.swift#L231

This could instead be written using guard let, which then avoids the repeated forced unwrapping.

(Parts are 3 year old swift code while others are 5 year old swift.)

Benefit:
 - increased readability
 - more accurately reflect our expectations of the state of the variables

**Comment by justin-stephenson** [comment]
Thank you @krugerk agreed we can cleanup some of this code, PRs are welcome !

**Comment by justin-stephenson** [comment]
Please submit a Pull Request for this.
