### ISSUE TITLE
Can't dismiss About screen on iOS 12

### ISSUE THREAD

**Issue by jmarshall** [freeotp/freeotp-ios#182]
On both a 2016 iPhone SE running iOS 12.4.1 and an iPad running iOS 12.x, the About screen does not respond to swiping in any direction and there are no buttons visible. The only way to dismiss the About screen is to force-quit the application.

(FreeOTP 2.1.)

**Comment by justin-stephenson** [comment]
Thanks for reporting this @jmarshall - the modal swipe down dismissal is only possible in iOS 13, apologies for the oversight. We will make sure it is fixed for the next minor release.
