### ISSUE TITLE
Sort the tokens

### ISSUE THREAD

**Issue by greenmoss** [freeotp/freeotp-ios#187]
Please allow tokens to be sorted:
* alphabetically
* by last use

Manual re-ordering is very challenging. Hard-pressing on a token to manually move it, results in the list of tokens moving by extremely rapidly. It is very hard to "drop" the token in the correct spot in the list.

This becomes an increasingly significant challenge, the more tokens are added to the list.

**Comment by justin-stephenson** [comment]
> Please allow tokens to be sorted:
> 
>     * alphabetically
> 
>     * by last use
> 
> 
> Manual re-ordering is very challenging. Hard-pressing on a token to manually move it, results in the list of tokens moving by extremely rapidly. It is very hard to "drop" the token in the correct spot in the list.
> 
> This becomes an increasingly significant challenge, the more tokens are added to the list.

Token reordering was improved in FreeOTP v2.2, please check and let me know if it helps.

**Comment by greenmoss** [comment]
Confirmed, manual reordering works fine now
