### ISSUE TITLE
Token description partly unvisible

### ISSUE THREAD

**Issue by mvreeburg** [freeotp/freeotp-ios#192]
Recently the design of free otp has been changed. Since then I can not see all of the token description wich makes it impossible to chose the right one. How can I see the full description and/or how can I change the description?
![F58FF545-C759-44B6-98A1-826A3CC50AC8](https://user-images.githubusercontent.com/69474832/89820179-e689a800-db4c-11ea-849b-73c6311a940f.png)

**Comment by justin-stephenson** [comment]
Could you provide the FreeOTP version, device model, and iOS version you are using? The font looks quite a bit larger than normal, I am not sure why that may be happening.

The token information is immutable after adding the token, you would need to remove-readd the token with the updated 'label' parameter in the token URI.

**Comment by mvreeburg** [comment]
Hi Justin,

Iphone 8
IOS: 13.5.1
FreeOTP 2.1

Met hartelijke groet,
Maarten Vreeburg
BIG-nr.: 29035395604

[1450077475747_2013]


Fysiotherapie – Diëtetiek – Ergotherapie - FysioFit
t. 0345 – 510124 | m. 06 – 20404786 | www.adfys.nl<http://www.adfys.nl/>

Ant. Van Lalainglaan 1,  4101 HS Culemborg
Koopmansgildeplein 6, 4105 TX Culemborg
Dr. Reilinghplein 14, 4141 DB Leerdam

ADFYS sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Indien de e-mail bij vergissing bij u is terecht gekomen, wilt u dan telefonisch contact met ons opnemen (+31 345 510124) en dit e-mail bericht terugsturen naar de afzender. Wij verzoeken u daarna dit e-mail bericht te vernietigen, de inhoud ervan niet te gebruiken en niet onder derden te verspreiden, omdat het bericht vertrouwelijke informatie kan bevatten, beschermd door een beroepsgeheim.
P Denk aan het milieu voordat u deze e-mail print.

________________________________
Van: Justin Stephenson <notifications@github.com>
Verzonden: maandag 10 augustus 2020 22:32
Aan: freeotp/freeotp-ios <freeotp-ios@noreply.github.com>
CC: Maarten Vreeburg | ADFYS Paramedisch Centrum <Maarten.Vreeburg@adfys.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [freeotp/freeotp-ios] Token description partly unvisible (#192)


Could you provide the FreeOTP version, device model, and iOS version you are using? The font looks quite a bit larger than normal, I am not sure why that may be happening.

The token information is immutable after adding the token, you would need to remove-readd the token with the updated 'label' parameter in the token URI.

**Comment by j15e** [comment]
Same here on iPhone Xs, iOS 14.0.1, free otp 2.1.

I can't distinguish anymore a lot of my tokens names... 😢

**Comment by justin-stephenson** [comment]
> Same here on iPhone Xs, iOS 14.0.1, free otp 2.1.
> 
> I can't distinguish anymore a lot of my tokens names... 😢

Would you mind posting a screenshot of the issue?

Thank you.

**Comment by mvreeburg** [comment]
I already posted a screenshot.
No solution offered so far.

Met hartelijke groet,
Maarten Vreeburg
BIG-nr.: 29035395604

[1450077475747_2013]


Fysiotherapie – Diëtetiek – Ergotherapie - FysioFit
t. 0345 – 510124 | m. 06 – 20404786 | www.adfys.nl<http://www.adfys.nl/>

Ant. Van Lalainglaan 1,  4101 HS Culemborg
Koopmansgildeplein 6, 4105 TX Culemborg
Dr. Reilinghplein 14, 4141 DB Leerdam

ADFYS sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Indien de e-mail bij vergissing bij u is terecht gekomen, wilt u dan telefonisch contact met ons opnemen (+31 345 510124) en dit e-mail bericht terugsturen naar de afzender. Wij verzoeken u daarna dit e-mail bericht te vernietigen, de inhoud ervan niet te gebruiken en niet onder derden te verspreiden, omdat het bericht vertrouwelijke informatie kan bevatten, beschermd door een beroepsgeheim.
P Denk aan het milieu voordat u deze e-mail print.

________________________________
Van: Justin Stephenson <notifications@github.com>
Verzonden: zaterdag 10 oktober 2020 15:28
Aan: freeotp/freeotp-ios <freeotp-ios@noreply.github.com>
CC: Maarten Vreeburg | ADFYS Paramedisch Centrum <Maarten.Vreeburg@adfys.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [freeotp/freeotp-ios] Token description partly unvisible (#192)


Same here on iPhone Xs, iOS 14.0.1, free otp 2.1.

I can't distinguish anymore a lot of my tokens names... 😢

Would you mind posting a screenshot of the issue?

Thank you.

**Comment by j15e** [comment]
It is problematic especially with AWS keys as they have a long description with a long and identical prefix : 

![IMG_5365](https://user-images.githubusercontent.com/143380/95779817-c5524e80-0c98-11eb-9b44-19134cbb8941.jpg)
![IMG_5366](https://user-images.githubusercontent.com/143380/95779899-efa40c00-0c98-11eb-9dc3-65399ead5eb0.PNG)

**Comment by justin-stephenson** [comment]
Thanks for the feedback, this should be fixed to handle longer account names in the next release. The use of upper-case characters makes the problem easier to reach the max width.

**Comment by xpaulz** [comment]
same issue here unable to see longer names, only now some of the names don’t appear at all, so I can’t even distinguish what used to be visible.

FreeOTP 2.1
iPhone 8 plus/3.7


![E443F573-69AA-49BC-8BB6-23759B46A99C](https://user-images.githubusercontent.com/2723612/96771167-2dd6b500-1396-11eb-879c-7cf90eaa58da.png)
