### ISSUE TITLE
Can’t create new 

### ISSUE THREAD

**Issue by kizorb** [freeotp/freeotp-ios#194]
After iOS 14 update I can no longer add new accounts. Only option is info or token for existing accounts.

**Comment by justin-stephenson** [comment]
Thank you for the report @kizorb 

I don't see any issues on my iPhone 11 on iOS 14.0.1, would you mind sending a screenshot of the issue? Note that manual entry was removed in FreeOTP v2.0 and later.

As a workaround you may try scanning a QR code with your camera and it should get forwarded to FreeOTP

**Comment by kizorb** [comment]
It’s possible that I was on an older version. I remember manually setting up one of my accounts.  I will lose this as No Issue Found.
