### ISSUE TITLE
Unable to Delete Account on iOS14

### ISSUE THREAD

**Issue by mattcobley** [freeotp/freeotp-ios#195]
I've just installed FreeOTP on an iPhone XR on iOS 14.0.1 and I don't have an option to remove any accounts that I add. In addition to viewing the codes, all I can do is scan a QR code to add an account, view the license information via the "i" in the top right, and re-order my entries by pressing and dragging.

**Comment by justin-stephenson** [comment]
> I've just installed FreeOTP on an iPhone XR on iOS 14.0.1 and I don't have an option to remove any accounts that I add. In addition to viewing the codes, all I can do is scan a QR code to add an account, view the license information via the "i" in the top right, and re-order my entries by pressing and dragging.

You can swipe right to present the confirmation action sheet to remove the token.

**Comment by mattcobley** [comment]
Thanks, you're absolutely right. Apologies for the waste of time. I think I tried starting to swipe one way or the other but normally I expect some sort of indicator mid-swipe as to what it is going to do, e.g. a red bin or similar in the space where the entry was, but didn't see anything so must've not tried the full swipe as a result.
