### ISSUE TITLE
Cannot delete token

### ISSUE THREAD

**Issue by andreaslif** [freeotp/freeotp-ios#196]
I started adding service, but didn’t finish it. However, the token was still aded in the app. Because I didn’t finish it the first time, I had to add it again, and now I have two entries for the same service and it’s annoying trying to remember which is actually in use. Especially since I can’t seem to change icon for them either.

**Comment by justin-stephenson** [comment]
@andreaslif Can you swipe the token right to remove the one you do not want?

**Comment by andreaslif** [comment]
Ah, yes. That worked. I tried swiping from right to left before, since that's the typical iOS behaviour.

Maybe it would be a good idea to change that? I think it would also be good if swiping just revealed the delete button underneath and then you have to tap that button to confirm the deletion. Like iOS Mail/notes/reminders etc. work. What do you think?

**Comment by justin-stephenson** [comment]
Yes agreed, I'd like to improve the 'removal' functionality but haven't had time to do so. I am considering using https://github.com/SwipeCellKit/SwipeCellKit for it

**Comment by andreaslif** [comment]
I see. Seems like this would work also? 
https://developer.apple.com/documentation/uikit/uiswipeactionsconfiguration

**Comment by justin-stephenson** [comment]
> I see. Seems like this would work also?
> https://developer.apple.com/documentation/uikit/uiswipeactionsconfiguration

This is a property of a table view, but our tokens view is using a collection view.
