### ISSUE TITLE
Cannot delete item

### ISSUE THREAD

**Issue by Greentash** [freeotp/freeotp-ios#197]
I use FreeOTP on iPhone 7Plus, iOS 14.0.1
I have lot of duplicated item than I cannot remove 
![885C3703-3391-4C99-8717-3DC23D532875](https://user-images.githubusercontent.com/5729518/98133151-272b6000-1eb5-11eb-8ce6-3106f1e8a2f7.png)

How please perform this delete? Thanks in advance

**Comment by justin-stephenson** [comment]
> I use FreeOTP on iPhone 7Plus, iOS 14.0.1
> I have lot of duplicated item than I cannot remove
> ![885C3703-3391-4C99-8717-3DC23D532875](https://user-images.githubusercontent.com/5729518/98133151-272b6000-1eb5-11eb-8ce6-3106f1e8a2f7.png)
> 
> How please perform this delete? Thanks in advance

Does a swipe right of the token bring up a 'Delete' confirmation?
