### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by daviesalex** [freeotp/freeotp-ios#202]
When having a large number of OTP sites, searching manually by Icon is annoying (especially when having multiple applications with the same Icon).

A quick ability to search (magnifying glass in the menu bar) would really help out here. As you type letters, the list of icons shown should change to only show the list that match what you entered.

**Comment by mul1sh** [comment]
@daviesalex Will implement the search for ios in the next few days then 🙂

**Comment by daviesalex** [comment]
Thanks @mul1sh ! I've asked the folk at bountysource.com to flip the bounty to point to this issue, since its pointless in the other issue as you pointed out.

**Comment by mul1sh** [comment]
Awesome thanks @daviesalex will keep you updated on my progress here 🙂

**Comment by alphashuro** [comment]
@daviesalex I've submitted [a PR for this](https://github.com/freeotp/freeotp-ios/pull/211)

**Comment by mul1sh** [comment]
Ok i've [implemented ](https://github.com/freeotp/freeotp-ios/pull/212) the search functionality in the navigation bar as required @daviesalex.  I added the search bar programatically as opposed to using the storyboard to avoid the issues noted [here](https://stackoverflow.com/a/42510531)

So on clicking the search icon, the app will display the search bar and filter the codes as you search as shown below
![appVideo](https://user-images.githubusercontent.com/2150634/99651537-c892e400-2a67-11eb-822d-5dab18328f5e.gif)

I'm now currently writing the tests for the functionality and also will fix a couple of other bugs I saw. So I will update my PR further with all these changes in the next few hours, thanks.

**Comment by daviesalex** [comment]
Great! @mul1sh that looks to meet our requirements perfectly. 
( @alphashuro without a screenshot demo i'm less sure what your PR does exactly, but hopefully the project maintainer can review both and merge one of them! )

**Comment by alphashuro** [comment]
Thanks @daviesalex I'll record a screenshot and add it!

**Comment by mul1sh** [comment]
@daviesalex thanks glad you like it 👍, I've updated my PR with the UI tests for search functionality, so now its ready for review 🙂
