### ISSUE TITLE
iOS asking for Touch ID 3X in latest update

### ISSUE THREAD

**Issue by OddHouseGames** [freeotp/freeotp-ios#204]
When using token or copying to clipboard on iOS iPhone 6S, it asks for Touch ID 3 times

To clarify, tokens ask you to use Touch ID 4 times in a row, while copying to clipboard asks 3 times in row.

**Comment by tomWhilbert** [comment]
Same experience as @Githubuxer 
ios 14.1
iphone Xr

**Comment by wilsonspoon** [comment]
iPhone 11, iOS 14.2 has the same bug, the app require FaceID for 3times.

**Comment by ldesgrange** [comment]
Similar problem but slightly worse. iPhone 6, iOS 12.4.8, FreeOTP 2.2.
When I select an account, FreeOTP asks for Touch ID, then nothing happens for a while, then the app crashes and I don't get the code.
One workaround is to select the account, "fill" the Touch ID, then double click on home button, select FreeOTP, there FreeOTP is asking again for Touch ID… and repeat TouchID/double home/FreeOTP until I get the code (about 3 times, sometimes the app still crashes).

**Comment by justin-stephenson** [comment]
Thank you for reporting this issue, I'm looking into it.

**Comment by justforissues** [comment]
same here, happens with passcode: asks for passcode 3 times in a row.

- iOS 14.2

**Comment by tkiral** [comment]
It has me authenticate 4 times: https://github.com/freeotp/freeotp-ios/issues/215

**Comment by justin-stephenson** [comment]
Hello, could you test and confirm that the following TestFlight build fixes this issue?

https://testflight.apple.com/join/kSkazqq7

**Comment by Githubuxer** [comment]
Yes, it works great! 👌🏻

**Comment by ldesgrange** [comment]
> Hello, could you test and confirm that the following TestFlight build fixes this issue?
> https://testflight.apple.com/join/kSkazqq7

Yes but it might be fixing it a bit too aggressively 😉… i.e. all my tokens are configured to be TouchID protected but now most of the time when touching one of the tokens, I get the code without being asked for TouchID.

**Comment by Githubuxer** [comment]
What OS is that? On iOS, all of my tokens are requiring TouchID using the test flight version.

**Comment by ldesgrange** [comment]
I'm on iPhone 6 with iOS 12.4.9, FreeOTP test flight (2.2.1).

**Comment by tkiral** [comment]
I no longer have to authenticate multiple times. I only have to authenticate for those apps I have it turned on for. Everything’s looking good for me.

Sent from my iPhone

On Nov 25, 2020, at 08:42, Laurent Desgrange <notifications@github.com> wrote:

﻿

I'm on iPhone 6 with iOS 12.4.9, FreeOTP test flight (2.2.1).

**Comment by tkiral** [comment]
Nope, nevermind. Dashlane and a few other apps are now not requesting TouchID verification. Nothing requests more than one time though.

Sent from my iPhone

On Nov 25, 2020, at 09:11, Taner Kiral <taner.kiral@hotmail.com> wrote:

﻿ I no longer have to authenticate multiple times. I only have to authenticate for those apps I have it turned on for. Everything’s looking good for me.

Sent from my iPhone

On Nov 25, 2020, at 08:42, Laurent Desgrange <notifications@github.com> wrote:

﻿

I'm on iPhone 6 with iOS 12.4.9, FreeOTP test flight (2.2.1).

**Comment by dsazonoff** [comment]
Just migrated from iPhone 11 to iPhone 12 with an encrypted backup. Got same issue: on 11 it requests Face ID for three times; on 12 it simply don't show protected codes.

**Comment by justin-stephenson** [comment]
> Just migrated from iPhone 11 to iPhone 12 with an encrypted backup. Got same issue: on 11 it requests Face ID for three times; on 12 it simply don't show protected codes.

This is expected behavior on backup and restore, I recently discovered the Apple keychain does not include the biometrics-locked keychain items in encrypted backups, for security reasons. This is not obvious to users however, I will add a warning on the Token wizard where you are prompted to clearly state locked tokens will not be included in backup.

**Comment by dsazonoff** [comment]
> This is expected behavior on backup and restore, I recently discovered the Apple keychain does not include the biometrics-locked keychain items in encrypted backups, for security reasons. This is not obvious to users...

Thanks, probably the best way is to add a feature to turn off ID lock for specific keys? So user can switch off Face ID, do a backup and restore it on another device. 
For me it's always a pain to migrate 2fa applications from one device to another.

**Comment by justin-stephenson** [comment]
This should be fixed now, Please file a new issue is the problem persists in the latest update.
