### ISSUE TITLE
Information page needs grey bar or arrow at top to indicate slide to close

### ISSUE THREAD

**Issue by OddHouseGames** [freeotp/freeotp-ios#205]
The information page needs a grey bar or arrow at top of the info slide-up page to indicate to user, slide to close to match other iOS UX flow. 

Currently it is just black, with nothing to indicate slide mechanic

**Comment by antdude** [comment]
In my old iPhone 6+ (iOS v12.4.9), I can’t get close/exit this info screen. I have to kill to restart the app. 😣
