### ISSUE TITLE
When registering a new QR code, "Brands" popup is very confusing

### ISSUE THREAD

**Issue by orev** [freeotp/freeotp-ios#206]
When scanning a QR code, the next step pops up a page that says "Brands", and then has a list of many icons. The term "Brands" is extremely confusing and does not tell the user what they are expected to do.

Please change this heading to something simple and obvious, like "Choose an icon".

**Comment by peterdd** [comment]
As user I even do not know what the purpose of Brands/"Choose an icon" should be.

I played/installed phpmyadmin in a local vagrant box, enabled 2fa there and it shows a generated qrcode, I scanned it using FreeOTP and this is shown by FreeOTP:

![freeotp](https://user-images.githubusercontent.com/1839154/108633225-6d5ffb80-7473-11eb-8ea2-4ee24fd4e54d.png)

So even my setup of phpmyadmin is messed up or the 2fa documentation of phpmyadmin lacks some important information, the FreeOTP should show some useful information what is going on and what the scanned qrcode means, right?

**Comment by grandopener** [comment]
Not sure if I should make a separate issue for this... but personally I don't mind the "brands" popup, except that it appears when this feature was introduced we lost the ability to choose custom images for new entries?  Unfortunately that killed the app for me--I need visual recognition of the sites' logos and choosing different abstract icons for various sites/companies not in the brands database isn't good enough.

**Comment by orev** [comment]
@grandopener That sounds like a separate issue. This one is about the Brands popup being extremely confusing and leaving users with no idea what they need to do on this screen. Allowing custom images would be a separate thing.

**Comment by justin-stephenson** [comment]
Thank you for the input, It would be great if someone would not mind submitting a PR for this.
