### ISSUE TITLE
Opening a 2FA with a password crashes the app

### ISSUE THREAD

**Issue by Firiyuu** [freeotp/freeotp-ios#207]
I set a password to my 2FA, when I click it, it takes my password, then the app crashes. The one with no password works

**Comment by Firiyuu** [comment]
This is giving me a headache.

I am locked out from my gitlab repo.

**Comment by justforissues** [comment]
same here, passcode locked 2FA does not accept passcode

- yes, passcode was entered correctly :)
- iOS 14.2
- most recent FreeOTP 2.2

**Comment by Firiyuu** [comment]
Can they unlock these for a while so we can use our accounts?

**Comment by justin-stephenson** [comment]
I reverted the changes which caused the locked tokens authentication problems, and posted a 2.2.1 release to the App store which has worked for some users. Unfortunately if the tokens are still not accessible it appears the OTP keychain item became corrupted in a way that prevents it from being retrieved properly in the keystore. In that case the only solution would be to remove and re-add the token. 

I am going to start providing TestFlight betas builds before upcoming releases are pushed to the App store, to avoid problems like this which aren't caught in my local device testing. Apologies for the troubles this caused.
