### ISSUE TITLE
After confirming touchid the app closes

### ISSUE THREAD

**Issue by Fallenlemon** [freeotp/freeotp-ios#214]
This happened after the latest update. When opening a password-protected token the app closes. If I start it again I'm stuck in this same loop. This is quite serious because i need this to/for work.
thanks

**Comment by justin-stephenson** [comment]
Could you test and confirm that the following TestFlight build fixes this issue?

https://testflight.apple.com/join/kSkazqq7

**Comment by tstimper** [comment]
confirmed, the issue is fixed in the TestFlight build on iOS 14.2 on iPhone SE (2020)

**Comment by justin-stephenson** [comment]
> This happened after the latest update. When opening a password-protected token the app closes. If I start it again I'm stuck in this same loop. This is quite serious because i need this to/for work.
> thanks

I reverted the authentication settings that were causing issues and pushed a 2.2.1 release to the app store, please check it.

**Comment by Fallenlemon** [comment]
Hi!

I tried it again and it crashed the first time, but worked on the second
attempt. 
Thanks!
