### ISSUE TITLE
Touch ID Multiple Requests

### ISSUE THREAD

**Issue by davinian** [freeotp/freeotp-ios#216]
Hi, great App, but after latest update v2.2 I have to use Touch ID **4 times** to access the codes! I have tried restarting the iPhone, but same issue - asked 4 times for Touch ID and then code is shown.

**Comment by justin-stephenson** [comment]
Hello,

Would you  mind checking to see if the following TestFlight build fixes this issue?

https://testflight.apple.com/join/kSkazqq7

**Comment by davinian** [comment]
Hi, thanks for the invite - I can confirm the v2.2.1 works as expected and requires only 1 Touch ID to access password protected tokens.

Thanks for speedy response.

Regards, David

**Comment by davinian** [comment]
Sorry - didn't mean to close the ticket :-)
