### ISSUE TITLE
No Access on iPhone 11 Pro

### ISSUE THREAD

**Issue by SoRoot** [freeotp/freeotp-ios#225]
Cant access my token. When I click the token nothing happens. Seems to me that it only affects the iPhone 11 Pro, since on my iPad Pro (4th Gen) it works without any problems. Both running Version 2.2.1.

Any help is appreciated. thx.

**Comment by RuEijk** [comment]
Hi,

I'm having the same issue on my iPhone 12. It only seems to affect tokens that require Face ID authentication to be revealed, as tokens that do not require the use of Face ID can be opened just fine.

This issue might be the same as #224.

**Comment by justin-stephenson** [comment]
Does this affect only existing tokens, or newly added tokens also? FreeOTP release v2.2 caused some problems for locked tokens, those issues are fixed now in 2.2.1 however if your phone updated to v2.2 prior to v2.2.1 the upgrade path may have caused corruption of those migrated/existing locked tokens. If that is the case then i'm afraid removing and re-adding the token would be the only fix, FreeOTP can't make changes to tokens after they are stored in the Apple keystore.

I have not seen any issues with locked tokens on my iPhone 11 with iOS 14.4, but i'll do more testing.

**Comment by RuEijk** [comment]
Thanks for replying! I just checked and I think you're right. New tokens can be added and opened as usual. It are just the older tokens that can't be opened anymore. These were added before v2.2.1, so it probably has to do with the upgrade path that you mentioned.

**Comment by SoRoot** [comment]
Can confirm. If I'am trying to add new tokens it works flawless. Thx for workaround.
