### ISSUE TITLE
Search bar transition/click suggestion

### ISSUE THREAD

**Issue by OddHouseGames** [freeotp/freeotp-ios#229]
The new search bar is great, the click transition/placement could potentially be improved:

- Adjust spacing of top bar elements so that screen doesn't rapidly shift down to make space when search bar appears.

Or

- Similar to the screen transition in the iOS Passwords menu when you click in the search bar, it gently transitions the screens down instead of the instant/rapid screen elements shift.

**Comment by justin-stephenson** [comment]
Thank you for the suggestions

**Comment by igor2890** [comment]
I am currently working on this issue. I propose to make the design as in the Mail, WhatsApp or Telegram application with dragging the list of tokens to open the search bar. How do you feel about removing the search button? This will simplify the code and unload the navigation bar. This will also allow us to move the buttons for manually adding a token and scanning a qr code to the left side of the navigation bar.

**Comment by justin-stephenson** [comment]
> 

Makes sense to me, @mul1sh do you have any concerns about this?
