### ISSUE TITLE
More than 9 digits doesn't work on IOS

### ISSUE THREAD

**Issue by sab24** [freeotp/freeotp-ios#230]
Hi,

Thank you for all the work with this project. I really like the idea of one time passwords and was trying out this app a while ago. It didn't work with more than 9 digits in IOS back then, and today I checked and saw the same the same situation, so I thought maybe you've missed this feature. I hope this has not been reported before and hope you developers stay motivated and happy to keep on working on this project :) I think the fields for digits on IOS is simply too short to fit in all the digits. Don't know if anyone uses that much digits anyway.

**Comment by justin-stephenson** [comment]
Correct, that is still the case here https://github.com/freeotp/freeotp-ios/blob/master/FreeOTP/OTP.swift#L73-L85

We haven't seen any typical 2FA services issuing OTP codes longer than 9 digits. PRs are welcome however.

**Comment by justin-stephenson** [comment]
Closing as I don't see any OTP services using 9 digit token codes.
