### ISSUE TITLE
Can’t View Tokens, Locked Out of Gitlab 

### ISSUE THREAD

**Issue by kforte318** [freeotp/freeotp-ios#232]
Hey all, 

So I saw this mentioned in the closed tickets that a user was having an issue where they were unable to view any of their tokens or copy them, locking them out of their device. I am currently having the same issue I believe. I’m on an iPhone 12 Mini, 14.4.2, with FreeOTP 2.3, and I can’t select a token to get a 2FA code. Thanks in advance!

Kevin

**Comment by aureliomuth** [comment]
Hi, I have exactly the same problem and I use an iPhone 12 mini too.

**Comment by kforte318** [comment]
Definitely hope someone sees this soon, because I could really use to get into Gitlab hahaha.

**Comment by justin-stephenson** [comment]
Could you send a screenshot of the issue? Was this following a backup and restore, or just during normal phone/app usage? I wonder if this is a problem related to the iPhone 12 mini?

**Comment by yuki-kawaharada** [comment]
Mine is iPhone SE and neither receive 2FA from gitlab as well.

**Comment by justin-stephenson** [comment]
> Hi, I also have an iPhone 12 Mini. When I click a row to highlight the numbers for copying, it seems to activate the Edit->drag to reorder functionality, but never highlights or copies the numbers. On my tokens that are locked, there's no way to unlock them because when I click the tile nothing happens. When I tap harder or double tap, it also "highlights" the row for the drag to reorder. Hopefully this helps, I'm locked out of my systems, so it would be good to get this fixed.

I commented about the token lock issue above. 

FreeOTP no longer automatically copies the token code to clipboard, you would need to click the icon at the right of the token cell which will prompt you to copy the code. 

Long-pressing the token should activate the token reordering, so I don't think there is a problem there?

**Comment by justin-stephenson** [comment]
Please re-open this ticket if it is still applicable.
