### ISSUE TITLE
Missing edit and add-token button on iOS 14.5.1

### ISSUE THREAD

**Issue by dahumph** [freeotp/freeotp-ios#235]
Is that intentionally? There is no add or edit button any more. Just the "scan QR code" button. I need to enter the Base32 secret manually as no QR availlable...

**Comment by merktassel** [comment]
Hi there! This is an issue I'd like to work -- however, I'm not sure what the user interface looked like before. Any chance you have a screenshot of the old version with the add and edit buttons present?

**Comment by AntiCompositeNumber** [comment]
Duplicate of #186, apparently intentional. For reference, the screenshot on https://freeotp.github.io/ still has it.

**Comment by igor2890** [comment]
@justin-stephenson I propose to close this issue, since the issue #138 is being resolved
