### ISSUE TITLE
Invalid authenticator code 

### ISSUE THREAD

**Issue by gowtham23gopal** [freeotp/freeotp-ios#236]

**Comment by gowtham23gopal** [comment]
After inputting the authenticator code on the website, the website prompts as invalid. However when I try it with another mobile, it works.

**Comment by tanmecolor** [comment]
Please check the time zone ( date and time settings) , this has to match the same zone you had when you added the token in the app .

**Comment by justin-stephenson** [comment]
Please re-open this issue if the problem still persists
