### ISSUE TITLE
Deleting token in FreeOTP

### ISSUE THREAD

**Issue by 97-dev** [freeotp/freeotp-ios#238]
Hello,
how can I delete a token in FreeOTP which I do not need anymore?

Thanks!

Kind regards

**Comment by egberts** [comment]
Mmmm, still an issue

**Comment by egberts** [comment]
Yeah. It does. 

Was half-expecting to hold finger down and getting some choice context menu.  But swipe works

**Comment by flowt-au** [comment]
Not obvious!
On Android version, swiping either direction does not do anything. 
1. tap the FreeOTP icon on the left of the token item. 
2. The icon changes to a tick and the top toolbar shows a delete (bin) icon
3. Then you get a confusing message about "Deleting a token does not disable it on the server"

Not sure what to do now. I wanted to remove a token and start again in the app that uses it, as-if I had not set up 2FA at all.
