### ISSUE TITLE
Cannot open GitLab bar to view 2FA code

### ISSUE THREAD

**Issue by timgraham2020** [freeotp/freeotp-ios#240]
Bug - Pressing the icon or anywhere on the bar is unresponsive. The info icon, search and QR code icons work. I can’t get into GitLab, which is a must have for work

**Comment by justin-stephenson** [comment]
What is meant by 'GitLab bar' exactly? Could you provide a screenshot or video of the issue?

**Comment by timgraham2020** [comment]
Thanks Justin,
I figured out the root cause (my 3rd party 2FA app). It’s fixed now. Apologies for not closing out this ticket earlier!

-Tim
