### ISSUE TITLE
Can’t generate Code on iPhone 12 Pro

### ISSUE THREAD

**Issue by Fixthispls** [freeotp/freeotp-ios#243]
It won’t access face id so there is no way to generate a code. @justin-stephenson 

Please fix this bug..

**Comment by justin-stephenson** [comment]
@Fixthispls can you provide a screenshot or video of this issue? Is it only a problem on the iPhone 12 Pro?

**Comment by Fixthispls** [comment]
I can’t provide a pic or video but i can say that i works on iphone 11..Gesendet mit der mobilen Mail AppAm 03.08.21 um 17:04 schrieb Justin Stephenson
                
            
            
                
                    Von: "Justin Stephenson" ***@***.***>Datum: 3. August 2021An: "freeotp/freeotp-ios" ***@***.***>Cc: "Mention" ***@***.***>,"Fixthispls" ***@***.***>Betreff: Re: [freeotp/freeotp-ios] Can’t generate Code on iPhone 12 Pro (#243)
                
                
@Fixthispls can you provide a screenshot or video of this issue? Is it only a problem on the iPhone 12 Pro?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/freeotp/freeotp-ios/issues/243#issuecomment-891922793",
"url": "https://github.com/freeotp/freeotp-ios/issues/243#issuecomment-891922793",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by justin-stephenson** [comment]
Okay thanks, I'll see if I can reproduce this issue with the iPhone 12 Pro emulator.

**Comment by onefastskater** [comment]
I have the same issue. Did a factory reset on my iPhone 12, restored phone state from backup 1-2 days old. Now several OTP icons display a small lock icon ( never noticed the icon before). When I select an icon no face recognition occurs.

**Comment by svillar** [comment]
So is there no way to access those tokens with the lock icon? In my case I also had to do a factory reset of the device.

I can click on the share button of some of them (not all) and then select copy to clipboard, but that does nothing because when pasting it somewhere else it just shows nothing.

**Comment by ithr0n** [comment]
I have exactly the Same issue and this is really urgent!!! I am Not able to login to my accounts and there is no way to reset MFA for these accounts. Please provide a solution or workaround as soon as possible!!!

**Comment by justin-stephenson** [comment]
Please re-open this issue if help is still needed. Locked tokens will not be included in backups, as Apple Biometrics secure data will not leave the device.
