### ISSUE TITLE
Access to tokens does not work some days after moving to new iPhone

### ISSUE THREAD

**Issue by tstimper** [freeotp/freeotp-ios#245]
Hi, 

we have a user who switches to a new iPhone with iOS 14.6.0 and FaceID
He was able to access all tokens for some days.
Today this stops working for existing entries, but he was able to scan an new token
and this works. 

FreeOTP version 2.3

**Comment by justin-stephenson** [comment]
This is expected behavior of biometric locked tokens due to Apple keychain security, we added a warning when you added a 'Locked' token to make this evident.

**Comment by tstimper** [comment]
ok, thank you, the user confirmed that this was the issue.
