### ISSUE TITLE
Unable to generate OTP

### ISSUE THREAD

**Issue by fignew** [freeotp/freeotp-ios#246]
After restoring my iPhone from an iCloud backup I can no longer select any of the three accounts I have in FreeOTP. I can see the accounts but nothing happens when click on them.

![image](https://user-images.githubusercontent.com/215998/128221983-731d2ff8-b0a5-4830-aa30-9fa87b268d81.jpeg)

Any help to get me back into my accounts would be appreciated.

**Comment by justin-stephenson** [comment]
This is expected behavior of biometric locked tokens due to Apple keychain security, we added a warning when you add a new 'Locked' token to make this evident.

**Comment by fignew** [comment]
So there is no way to unlock?

**Comment by fignew** [comment]
Seems that there is not.
Unfortunately the warning was added after I created the tokens :(

Time to send my drivers license to Amazon (woohoo!)
