### ISSUE TITLE
TOTP interval other than 60s

### ISSUE THREAD

**Issue by johnwmail** [freeotp/freeotp-ios#247]
Hi, when I use freeopt on android, I can setup interval other than 60s (eg: 3600s / 1h).
but I cannot find this on IOS version.
Is IOS version support setup interval other than 60s?

And how to import my export from android?
Thanks.

**Comment by justin-stephenson** [comment]
Can you try testing the various `period` intervals from

https://freeotp.github.io/qrcode.html

**Comment by johnwmail** [comment]
> Can you try testing the various `period` intervals from

I would like to set it 3600s (1 hour), Android version support it.
![image](https://user-images.githubusercontent.com/1752235/128874496-5ae2fb7a-ab9a-40cb-b8a3-85e6610edb6d.png)

**Comment by johnwmail** [comment]
> Can you try testing the various `period` intervals from
> 
> https://freeotp.github.io/qrcode.html

Manually update the code, it work, thanks.
![image](https://user-images.githubusercontent.com/1752235/128876317-5d653970-a1b5-40b9-963a-d57b4caa42be.png)

**Comment by justin-stephenson** [comment]
@johnwmail Would you mind submitting a Pull request here? https://github.com/freeotp/freeotp.github.io

**Comment by johnwmail** [comment]
> @johnwmail Would you mind submitting a Pull request here? https://github.com/freeotp/freeotp.github.io

Hi, I would but to be honestly, I don't think patch like this is useful for anyone (even for me).
If I am the developer, and see some one submit patch like this, I must ask "why we need add 1 hour option? and why not add 2 hours option ... etc".
so, I will submit a pull request, when I create the "editable interval input" patch. (but I don't know HTML/JS too much).
