### ISSUE TITLE
help to install the freeotp on macbook with xcode

### ISSUE THREAD

**Issue by Peter8200** [freeotp/freeotp-ios#248]
Dear,

Where can i find the procedure to install the freeotp on my macbook with X-code.
I would like to know how this work and eventually trying to participate in some development to a new release.

I tried with everything I found on the internet but when trying to run i got following build error with importing TinyConstraints...

Thanks.

Peter.

**Comment by stefounet** [comment]
Same here, would be great to have a little pointer on how to start!

**Comment by justin-stephenson** [comment]
Hi,

It should be enough to git clone the` freeotp-ios` repository, then run the carthage commands mentioned in the README: https://github.com/freeotp/freeotp-ios#install-build-dependencies

What errors are you seeing?

**Comment by stefounet** [comment]
I'll give a try with the new Readme! Thank you!

**Comment by justin-stephenson** [comment]
Please re-open this issue if any help is needed.
