### ISSUE TITLE
App does not work without access to the camera

### ISSUE THREAD

**Issue by xorcare** [freeotp/freeotp-ios#250]
I have denied access to the camera and I am unable to add a new token on my iPhone 11 as the app stops on the next screen:

![IMG_D6485D19D79A-1](https://user-images.githubusercontent.com/8522475/135661494-c66d29bd-9b0b-4e9f-bb1d-e878bf4212a5.jpeg)

**Comment by JacksonTaylorxyz** [comment]
I am having a similar issue. I have a OnePlus 7 pro on Android, and my cameras have recently stopped working. I am unable to open FreeOTP, it just crashes. Not 100% sure if this is related, but I haven't had this issue until now.

**Comment by justin-stephenson** [comment]
Currently, the only way to add tokens is scanning a QR code. We have an Issue open for adding manual entry support. Please re-open this issue if any further help is needed.
