### ISSUE TITLE
Free otp unresponsive 

### ISSUE THREAD

**Issue by Syunchua** [freeotp/freeotp-ios#257]
I clicked the only otp I had in the app and it doesn’t work, at all, there’s nothing on the app the trouble shoot the issue either, need help

**Comment by Norjek** [comment]
Hi Syunchua
Can you give more details to the developers? E.g. which version of the app and which version of iOS on which device type you're using?
Can you add another OTP Token and does that one work?
Best regards

**Comment by CoreyScogin** [comment]
I had a similar issue on iOS **15.2** when photo access was turned off. 
FreeOTP would either not start (only show the splash screen) or freeze a few moments after opening.
Allowing access to some or all photos resolved the issue.

I have been unable to reproduce the issue on iOS **15.2.1** regardless of the photo access settings.

**Comment by justin-stephenson** [comment]
Please re-open this issue if any help is still needed.
