### ISSUE TITLE
Show token name when swipe to delete

### ISSUE THREAD

**Issue by OddHouseGames** [freeotp/freeotp-ios#259]
It would be beneficial to list the token name when you swipe to delete, to reduce the chances of deleting a token by mistake.

I often exit the interaction and do it again just to ensure I’ve swiped the correct one, since there is no identifying information during the process.

**Comment by egberts** [comment]
Apple usually does the swipe left which brings up a red button labeled "Delete". 

You could still show the token name during this state of "delete prompt".
