### ISSUE TITLE
Cannot unlock token in iOS 15.1

### ISSUE THREAD

**Issue by LimDul99** [freeotp/freeotp-ios#264]
I use FreeOTP on an iPhone SE, iOS 15.1 for just one token that I don't need very often (but that still is crucially important to me). When recently trying to create a token, I realized that the token islocked, i.e. it displays a small lock in the bottom left corner and when I tap on it, nothing happens. It seems similar to what is described in #261 (I cannot attach a screenshot as that would show personal data).

However, unlike in #261 and others, I did not change my phone, restore a backup or anything of the kind. The only change that I made since it last worked and that I can think of is the update from iOS 14.x to 15.1. I urgently need access to the account the token is created for and can't seem to find an answer to this problem anywhere.

**Comment by justin-stephenson** [comment]
I would suggest trying to reconfigure/setup your iOS Face ID (or passcode if you don't use Face ID) authentication on your device, if that doesn't work then it sounds like the token keychain data somehow got corrupted or lost. 

I know it is not straightforward, but you could potentially also try to revert back to iOS 14.x

Sorry for the issue you had, I would be interested to know more detail if there is any idea of how to reproduce the problem.

**Comment by justin-stephenson** [comment]
@LimDul99 any luck?
