### ISSUE TITLE
Application does not start after iOS update 15.3

### ISSUE THREAD

**Issue by olivettiwetti** [freeotp/freeotp-ios#266]
After the latest iOS update last night I can no longer start the FreeOTP application on my iPhone 13,1. The version I used up to now is 2.3 and I never had issues starting it.

The console shows: 
```
...
error		FreeOTP	Failed to open photo library <private>, Error Domain=com.apple.photos.error Code=41011 UserInfo={NSLocalizedDescription=<private>}
error		FreeOTP	Got a bind failure for URL <private>, resetting bind state: <private> (previous result: (null))
fault		FreeOTP	XPC connection error to assetsd <private> : Error Domain=com.apple.photos.error Code=41011 UserInfo={NSLocalizedDescription=<private>}
default		FreeOTP	Creating blackhole proxy for <private> from proxy factory <private> for library URL: <private>
error		FreeOTP	Swallowing proxy invocation: <private> <private>
default		FreeOTP	XPC:  Unable to create NSXPCConnection
error		FreeOTP	fault: Something has gone badly awry initializing the XPC connection pool: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
fault		FreeOTP	CoreData: Something has gone badly awry initializing the XPC connection pool: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
default		FreeOTP	CoreData: XPC: sendMessage: failed #0
default		FreeOTP	CoreData: XPC: sendMessage: failed #1
default		FreeOTP	CoreData: XPC: sendMessage: failed #2
default		FreeOTP	CoreData: XPC: Unable to sendMessage: to server
default		FreeOTP	CoreData: XPC: sendMessage: failed #3
default		FreeOTP	CoreData: XPC: sendMessage: failed #4
default		FreeOTP	CoreData: XPC: sendMessage: failed #5
default		FreeOTP	CoreData: XPC: sendMessage: failed #6
default		FreeOTP	CoreData: XPC: sendMessage: failed #7
```
Afterwards it stops.

Let me know if you need further information.

**Comment by justin-stephenson** [comment]
> After the latest iOS update last night I can no longer start the FreeOTP application on my iPhone 13,1. The version I used up to now is 2.3 and I never had issues starting it.
> 
> The console shows:
> 
> ```
> ...
> error		FreeOTP	Failed to open photo library <private>, Error Domain=com.apple.photos.error Code=41011 UserInfo={NSLocalizedDescription=<private>}


This error sounds like https://github.com/freeotp/freeotp-ios/issues/258 - please check of the testflight build works for you or not.

**Comment by olivettiwetti** [comment]
Great! I didn't see that issue. Thanks for having shared it.
Yes, I can confirm: The testflight build works also for me! Before I installed the testflight build, I tried if it worked by sharing 1 single photo, which also worked.

Thank you very much!
