### ISSUE TITLE
Update Fedora logo with new logo and change background colour

### ISSUE THREAD

**Issue by jessicachitas** [freeotp/freeotp-ios#309]
Hi there! 

My name is Jess Chitas and I am from the Fedora Design team. 

I noticed that the logo that you have for the Fedora OTP is out of date and we would like if it was changed to the new logo. Attached is an SVG and PNG of the logo that we would like you to use.

Another issue as well is the background colour that is not within our brand guidelines. The colour we would like to change it to would be **#51a2da** which is the New Fedora Blue.

Thank you!

![fedora-logo-replacement-for-otp](https://github.com/freeotp/freeotp-ios/assets/36636982/feaefa94-0662-4024-8a46-943c78315b71)
![fedora-logo-replacement-for-otp](https://github.com/freeotp/freeotp-ios/assets/36636982/9c3ea90f-50ab-472c-8b71-9e140bb485a1)

**Comment by mairin** [comment]
commenting for follow

**Comment by justin-stephenson** [comment]
@jessicachitas Thank you, I will make sure to update our logo and background color. I suspect the same should be done for https://github.com/freeotp/freeotp-android

**Comment by jessicachitas** [comment]
Hi @justin-stephenson , yes please! Will I file a ticket in there as well?

**Comment by justin-stephenson** [comment]
> Hi @justin-stephenson , yes please! Will I file a ticket in there as well?

Yes please.

**Comment by justin-stephenson** [comment]
Android PR submitted here https://github.com/freeotp/freeotp-android/pull/366

I will submit the iOS PR soon.

**Comment by Neustradamus** [comment]
@justin-stephenson: Nice!

Can you help to solve other iOS problems too?

**Comment by justin-stephenson** [comment]
It appears the FontAwesome library we are using in iOS has not been updated in some time (https://github.com/thii/FontAwesome.swift/issues/281) so we may need to stop depending on this external library.

**Comment by justin-stephenson** [comment]
> It appears the FontAwesome library we are using in iOS has not been updated in some time ([thii/FontAwesome.swift#281](https://github.com/thii/FontAwesome.swift/issues/281)) so we may need to stop depending on this external library.

Perhaps we can use https://github.com/LiveUI/Awesome - if not we could add the FontAwesome icon kit into the iOS project but then we have to manually update it each time there is a new FontAwesome icon set.

**Comment by justin-stephenson** [comment]
This will be fixed when https://github.com/freeotp/freeotp-ios/pull/329 is included in a new release.

**Comment by Neustradamus** [comment]
@justin-stephenson: Good job!

Can you look other important tickets?
- https://github.com/freeotp/freeotp-ios/issues/252
- https://github.com/freeotp/freeotp-android/issues/345

Thanks in advance.
