### ISSUE TITLE
Move away from moa and FontAwesome libraries 

### ISSUE THREAD

**Issue by justin-stephenson** [freeotp/freeotp-ios#322]
Both libraries are no longer maintained.

https://github.com/thii/FontAwesome.swift/issues/287

https://github.com/evgenyneu/moa/issues/23

**Comment by justin-stephenson** [comment]
Fixed in master.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/freeotp/freeotp-ios/pull/329
- https://github.com/freeotp/freeotp-ios/pull/330
- https://github.com/freeotp/freeotp-ios/pull/331
- https://github.com/freeotp/freeotp-ios/pull/332
