### ISSUE TITLE
Possible issue with invalid image parameter

### ISSUE THREAD

**Issue by volinthius** [freeotp/freeotp-ios#340]
Assuming that we input a QR code that resolves to this kind of key URI the application is stuck crashing on startup:

`otpauth://totp/Example%20Something:john.doe@example.com?secret=EHH4EHH4EHH4EHH4EHH4EHH4EHH4EHH4EHH4EHH4EHH4EHH4EHH4&issuer=Example%20Something&image=undefined/images/example.png`

Seen on iOS with FreeOTP 2.3.4.

**Comment by volinthius** [comment]
I assume that the token is stored with the invalid `image` parameter. And furthermore I assume that when [`TokenViewController`](https://github.com/freeotp/freeotp-ios/blob/master/FreeOTP/TokensViewController.swift) tries to download the image an error happens in [`ImageDownloader`](https://github.com/freeotp/freeotp-ios/blob/master/FreeOTP/ImageDownloader.swift) with the missing scheme:

```
func fromURL(_ url: URL, _ iv: UIImageView, completion: @escaping (UIImage) -> Void) {
        switch url.scheme! {
```

**Comment by justin-stephenson** [comment]
@volinthius does this occur for any 'issuer' value present in the Token URI? With added FontAwesome icon support the 'image' URI is not commonly used but this is a bug that needs to be fixed.

**Comment by volinthius** [comment]
Unfortunately the application is stuck crashing on startup even after removing (with data removed as well) and reinstalling. So I cannot retry with another issuer.
