### ISSUE TITLE
FreeOTP crashes on launch

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-ios#35]
**Reported by airwave on 1 Aug 2014 13:47 UTC**
Yesterday I installed FreeOTP and added some OTPs to it. Today when I try to launch it, I get "Unfortunately, FreeOTP has stopped." Attached is a logcat for the crash. Please let me know if there's any more information I can help with.

**Comment by npmccallum** [comment]
**Comment by airwave on 2 Sep 2014 11:12 UTC**
This issue still exists in 1.5.

**Comment by justin-stephenson** [comment]
Closing as outdated.
