### ISSUE TITLE
Crash with improper otpauth:// urls

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-ios#41]
**Reported by mathstuf on 21 Sep 2014 17:18 UTC**
I made a malformed URL and tried to scan it with FreeOTP and got a crash:

    otpauth://totp/?secret=...

I'm guessing that the username is assumed to be non-empty somewhere.

**Comment by justin-stephenson** [comment]
Closing as outdated, this should be resolved in FreeOTP v2.0.
