### ISSUE TITLE
Every OTP generation results in true dialer number search

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-ios#66]
**Reported by coolsvap on 1 Jul 2015 08:18 UTC**
Everytime I generate an otp the true dialer number search is invoked by default.

**Comment by npmccallum** [comment]
**Comment by coolsvap on 1 Jul 2015 15:32 UTC**
I have found the root cause for the issue. After every OTP generation, the OTP is copied by default which leads to this issue. If I turn off the true dialer service cron job to actively monitor numbers in clipboard, the issue does not come.

**Comment by justin-stephenson** [comment]
Closing as outdated.
