### ISSUE TITLE
Can not add second Slack account

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-ios#67]
**Reported by pla on 16 Jul 2015 12:20 UTC**
When I scan the QR for a second Slack (https://slack.com/) account FreeOTP doesn't add a new entry. FreeOTP seems to think it is the same as the first Slack account (guessing). My phone is a Asus Zenfone 2 model ASUS_Z00AD. I tried this with ADB logcat running but I didn't see anything interesting. Thanks, PLA

**Comment by lazzurs** [comment]
👍 

To get this to work I had to enter the code rather than scanning the QR code.

**Comment by tberton** [comment]
Same issue on iOS app. Workaround as described by @lazzurs also works on the iOS app.

**Comment by lazzurs** [comment]
I have just tested and this now works for me just fine. Can confirmed closed on iOS.

**Comment by npmccallum** [comment]
@lazzurs Thanks!
