### ISSUE TITLE
Remove unnecessary permissions

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-ios#75]
**Reported by dbrgn on 14 Jun 2016 12:15 UTC**
The INTERNET and READ_EXTERNAL_STORAGE permissions seem to be unused. They should be removed.

Patch is attached. Alternatively, you can pull from my fork:

$ git remote add dbrgn https://github.com/dbrgn/freeotp
$ git pull dbrgn/master

(I know people that did not want to use FreeOTP because it used the internet permission.)

**Comment by npmccallum** [comment]
**Comment by feddy on 29 Jul 2016 15:13 UTC**
I'm also wary of the app because of these required permissions, please merge this patch.

**Comment by justin-stephenson** [comment]
Closing as outdated, this was an android reported issue.
