### ISSUE TITLE
Can't add custom icons with iOS 11.1.2

### ISSUE THREAD

**Issue by tkaehn** [freeotp/freeotp-ios#93]
Can't add custom icons with iOS 11.1.2. Tapping on 'Change Icon' just shows an empty screen with 'Cancel' and 'Default' at the top.

**Comment by omkensey** [comment]
On iOS 11.2 I see a flash of the usual photo selection interface, then I get what @tkaehn describes.

**Comment by Peter8200** [comment]
Same problem see shortly all the all the albums and then a blank white screen with option Cancel / Default.  No I have a lot of items without image and its very hard to find the correct one.  Using a icon helps to find the correct one easily.
I tried all the iphone settings, privacy, accessess but nothing resolve this problem.
Hopely they find soon a solution. Thanks.

**Comment by prwater** [comment]
Same problem with iOS 11.2.6.

**Comment by emmanuelbernard** [comment]
Looks loke the app does not ask for the photo access permission.

**Comment by omkensey** [comment]
It already had read and write permission to the photo album on my phone when I just looked.

**Comment by Exaybachay** [comment]
iOS 11.2.6 problem still persist.

**Comment by Peter8200** [comment]
Is there someone that can resolve this problem ? Someone from Redhat ?

**Comment by BreakfastSerial** [comment]
I also have the same issue, the app flashes the photos on the device, then prompts the buttons for `cancel` or `default`.

**Comment by nickbe** [comment]
Nobody seems to care about bugs here. Project dead?

**Comment by nickbe** [comment]
Does anyone about alternatives to FreeOTP on iOS ?

**Comment by emmanuelbernard** [comment]
I ended up using the non open source OTP Auth app.

**Comment by tkaehn** [comment]
I am using https://mattrubin.me/authenticator/ which is also available on GitHub: https://github.com/mattrubin/Authenticator

**Comment by nickbe** [comment]
Thanks. Installed and tested. I like that one.

**Comment by Peter8200** [comment]
Even with version ios 12.1 is it not possible to attach an image.
For me and all my colleagues it would very usefull it's this should work again.
It has worked at the beginning.
Is there is nobody that can resolve this problem.  Is there no programmer at Red Hat company who can once modify this app.  The app is still version 1.1. since 4 years.
In our firm there are a lot of people (100)  that uses this app several time a day. 
Thanks a lot.......

**Comment by sabbaka** [comment]
@Peter8200 sorry for that. I recently started to work on FreeOTP. I plan to resolve this issue ASAP.

**Comment by justin-stephenson** [comment]
Closing as outdated, `FreeOTP v2.0` supports a new token icon feature using [FontAwesome](https://fontawesome.com) icons.
